[package]
name = "pm_amm"
version = "1.0.0"
authors = []

[addresses]

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "af263064d06de76969d5d63f8ceb99aa9883d58e"
subdir = "aptos-framework"

[dev-dependencies]
